stages:
  - build
  - test

build-code-job:
  stage: build
  retry: 2
  tags:
    - vehicle
  script:
    - echo "execute build job"
    - source /opt/ros/melodic/setup.bash
    - cd /home/path/planner_ws 
    - colcon build 


test-code-job:
  cache: {}
  stage: test
  retry: 2
  tags:
    - simulation
  script:
    - echo "Starting test"
    - "cd C:/mchp-parking-east/mchp_parking_east"
    - Powershell -File run_tests.ps1

  

  
